In [1]:
import tensorflow as tf
import numpy as np

In [2]:
from google.colab import files
uploaded = files.upload()

Saving data-04-zoo.csv to data-04-zoo.csv


In [4]:
xy = np.loadtxt('data-04-zoo.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(x_data.shape, y_data.shape)

'''
(101, 16) (101, 1)
'''

nb_classes = 7  # 0 ~ 6

# Convert y_data to one_hot
y_one_hot = tf.keras.utils.to_categorical(y_data, nb_classes)
print("one_hot:", y_one_hot)

tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(units=nb_classes, input_dim=16, activation='softmax'))
tf.model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.SGD(lr=0.1), metrics=['accuracy'])
tf.model.summary()

history = tf.model.fit(x_data, y_one_hot, epochs=1000)

# Single data test
test_data = np.array([[0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0]]) # expected prediction == 3 (feathers)
test_predict = tf.model.predict(test_data)
print(test_predict, tf.keras.backend.eval(tf.argmax(test_predict, axis=1)))

# Full x_data test
pred = tf.keras.backend.eval(tf.argmax(tf.model.predict(x_data), axis=1))
for p, y in zip(pred, y_data.flatten()): # this case don't need flatten()
    print("[{}] Prediction: {} True Y: {}".format(p == int(y), p, int(y)))

(101, 16) (101, 1)
one_hot: [[1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/gradient_descent.py:102: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(SGD, self).__init__(name, **kwargs)


Epoch 1/1000
4/4 [==============================] - 1s 4ms/step - loss: 1.7044 - accuracy: 0.3168
Epoch 2/1000
4/4 [==============================] - 0s 3ms/step - loss: 1.2269 - accuracy: 0.6139
Epoch 3/1000
4/4 [==============================] - 0s 3ms/step - loss: 1.1139 - accuracy: 0.7030
Epoch 4/1000
4/4 [==============================] - 0s 3ms/step - loss: 1.0211 - accuracy: 0.7327
Epoch 5/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.9498 - accuracy: 0.7228
Epoch 6/1000
4/4 [==============================] - 0s 4ms/step - loss: 0.8989 - accuracy: 0.8020
Epoch 7/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.8364 - accuracy: 0.8020
Epoch 8/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.8056 - accuracy: 0.8020
Epoch 9/1000
4/4 [==============================] - 0s 2ms/step - loss: 0.7533 - accuracy: 0.8218
Epoch 10/1000
4/4 [==============================] - 0s 3ms/step - loss: 0.7212 - accuracy: 0.8515
Epoch 11/1000
4/4 [