In [2]:
import tensorflow as tf
import numpy as np

In [4]:
from google.colab import files
uploaded = files.upload()

Saving data-01-test-score.csv to data-01-test-score.csv


In [7]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# Make sure the shape and data are OK
print(x_data, "\nx_data shape:", x_data.shape)
print(y_data, "\ny_data shape:", y_data.shape)

# data output
'''
[[ 73.  80.  75.]
 [ 93.  88.  93.]
 ...
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
x_data shape: (25, 3)
[[152.]
 [185.]
 ...
 [149.]
 [192.]] 
y_data shape: (25, 1)
'''
tf.model = tf.keras.Sequential()
# activation function doesn't have to be added as a separate layer. Add it as an argument of Dense() layer
tf.model.add(tf.keras.layers.Dense(units=1, input_dim=3, activation='linear'))
# tf.model.add(tf.keras.layers.Activation('linear'))
tf.model.summary()

tf.model.compile(loss='mse', optimizer=tf.keras.optimizers.SGD(lr=1e-5))
history = tf.model.fit(x_data, y_data, epochs=2000)

# Ask my score
print("Your score will be ", tf.model.predict([[100, 70, 101]]))
print("Other scores will be ", tf.model.predict([[60, 70, 110], [90, 100, 80]]))

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
x_data shape: (25, 3)
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]] 
y_data shape: (25, 1)
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 4         
                                                                 
Total params: 4
Tr

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/gradient_descent.py:102: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(SGD, self).__init__(name, **kwargs)


Epoch 1/2000
1/1 [==============================] - 1s 522ms/step - loss: 8509.2441
Epoch 2/2000
1/1 [==============================] - 0s 6ms/step - loss: 3152.8779
Epoch 3/2000
1/1 [==============================] - 0s 5ms/step - loss: 1172.4790
Epoch 4/2000
1/1 [==============================] - 0s 5ms/step - loss: 440.2699
Epoch 5/2000
1/1 [==============================] - 0s 6ms/step - loss: 169.5502
Epoch 6/2000
1/1 [==============================] - 0s 6ms/step - loss: 69.4563
Epoch 7/2000
1/1 [==============================] - 0s 5ms/step - loss: 32.4472
Epoch 8/2000
1/1 [==============================] - 0s 8ms/step - loss: 18.7625
Epoch 9/2000
1/1 [==============================] - 0s 5ms/step - loss: 13.7014
Epoch 10/2000
1/1 [==============================] - 0s 4ms/step - loss: 11.8287
Epoch 11/2000
1/1 [==============================] - 0s 4ms/step - loss: 11.1349
Epoch 12/2000
1/1 [==============================] - 0s 4ms/step - loss: 10.8769
Epoch 13/2000
1/1 [========